### ISSUE TITLE
optimus.Utilities().read_csv() functions builds a DF with some issues on DataBricks

### ISSUE THREAD

**Issue by denisarnaud** [ironmussa/Optimus#193]
Trying to implement the code of the [last blog post about Machine Learning with Optimus](https://becominghuman.ai/machine-learning-with-optimus-2f27f205a292) on a DataBricks (hosted Spark) environment, the following creation of a DataFrame by the ``op.Utilities().read_csv()`` method produces some errors.
```python
df_cancer = tools.read_csv("/mnt/data-science/induction/optimus-spark/data_cancer.csv")
```
 
The line provoking the error is:
```python
df_predict, gbt_model = op.ml.gbt(df_cancer, columns, "diagnosis")
org.apache.spark.SparkException: Checkpoint RDD has a different number of partitions from original RDD. Original RDD [ID: 1595, num of partitions: 1]; Checkpoint RDD [ID: 1600, num of partitions: 0].
```
Supported by:
```python
df_cancer.checkpoint()
df_cancer.count()
org.apache.spark.SparkException: Checkpoint RDD has a different number of partitions from original RDD. Original RDD [ID: 1603, num of partitions: 1]; Checkpoint RDD [ID: 1604, num of partitions: 0].
``
`

By the way, the following way to download the data and create the DataFrame would fail as well:
```python
df_cancer = tools.read_url("https://raw.githubusercontent.com/ironmussa/Optimus/master/tests/data_cancer.csv")
Downloading 'data_cancer.csv' from https://raw.githubusercontent.com/ironmussa/Optimus/master/tests/data_cancer.csv
Downloaded 125205 bytes
Creating pySpark DataFrame for 'data_cancer.csv'. Please wait...
Loading file using 'SparkSession'
Successfully created pySpark DataFrame for 'data_cancer.csv'
AnalysisException: 'Path does not exist: dbfs:/tmp/tmps20_77hz;'
```

So, it seems like the op.Utilities() methods do not write correctly temporary files on the underlying HDFS system on DataBricks.

**Comment by mrchristine** [comment]
Databricks doesn't use HDFS as the distributed storage layer. We use S3 and a wrapper called DBFS. It looks like the Utilities() function is attempting to read a mount point, and prefixing the path with `/dbfs/` may resolve this issue. See the docs here: https://docs.databricks.com/user-guide/dbfs-databricks-file-system.html 
read_csv() may be attempting to read from the local filesystem. The local filesystem has a fuse mount to the mounted databricks paths.

**Comment by argenisleon** [comment]
Hi @mrchristine, it seems that you have a very clear idea of how to solve this. Would you like to contribute? :)

**Comment by mrchristine** [comment]
I'm not too familiar with this module. Taking a quick look, running this package on distributed systems will try to load the downloaded dataset by the default filesystem. On Databricks, that would be DBFS / S3. This is why the exception shows the path error for `dbfs:/tmp/`. I'd recommend adding the `file:/` prefix to the path in this location. This should resolve the issue. 
https://github.com/ironmussa/Optimus/blob/eb4788acdbb89f4949db185c323413c10ef6bd1a/optimus/utilities.py#L98

**Comment by denisarnaud** [comment]
Thanks @mrchristine!
Note that adding a ``file:/dbfs`` prefix to the file-path does not solve the issue, as shown below:
```python
df_cancer = tools.read_csv("file:/dbfs/mnt/data-science/induction/optimus-spark/data_cancer.csv")
df_predict, gbt_model = op.ml.gbt(df_cancer, columns, "diagnosis")
org.apache.spark.SparkException: Checkpoint RDD has a different number of partitions from original RDD. Original RDD [ID: 566, num of partitions: 1]; Checkpoint RDD [ID: 571, num of partitions: 0].
```
```python
df_cancer.checkpoint()
df_cancer.count()
org.apache.spark.SparkException: Checkpoint RDD has a different number of partitions from original RDD. Original RDD [ID: 574, num of partitions: 1]; Checkpoint RDD [ID: 575, num of partitions: 0].
```

So, the above-mentioned solution may not fix the issue.

**Comment by FavioVazquez** [comment]
Yes these problems are present using databricks. Can you try it somewhere else please? Let me know please @denisarnaud

**Comment by mrchristine** [comment]
It looks like a similar issue as I explained above with the checkpoint directory. Unless you explicitly set the checkpoint directory, then it saves the checkpoint to the local filesystem. Running on Databricks, the workers are on a different machine and unable to fetch the checkpoint.
